name: Iteruj po gałęziach

on: push

jobs:
  super-lint:
    name: linie kodu
    runs-on: ubuntu-latest
  
    steps:
      - name: Pobierz gałęzie
        uses: actions/checkout@v2

      - name: wykonj Iterowanie
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
