name: Budowanie .exe

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 21 * * 53" # Uruchomienie raz w tygodniu o północy w niedzielę
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Sprawdź repozytorium
      uses: actions/checkout@v2

    - name: Skonfiguruj Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x" # Wybierz odpowiednią wersję Pythona

    - name: Zainstaluj zależności
      run: |
        pip install -r requirements.txt
        # Dodaj tutaj inne komendy instalacyjne, jeśli są potrzebne

    - name: Zbuduj plik .exe
      run: |
        # Dodaj tutaj komendy budujące plik .exe, np.:
        # python build.py

    - name: Prześlij plik .exe
      uses: actions/upload-artifact@v3
      with:
        name: wygenerowany-plik
